### ISSUE TITLE
Erreur si synchro de fichiers vers Nuxeo LTS2015 

### ISSUE THREAD

**Issue by hjacob35** [EsupPortail/esup-SyncFSNX#3]
Test effectué sur une plate-forme Nuxeo 7.10 (LTS2015) avec les paramètres suivants: 

# localisation du répertoire local synchroniser sur Nuxeo
localPath=/data/SIDES/Enseignants/Documents
# destination sur Nuxeo
remotePath=/default-domain/workspaces/testSyncFSNX
# uid de l'utilisateur Nuxeo
user=p-theses
# password de l'utilisateur Nuxeo
password=xxxxxxxx
# URL du serveur Nuxeo
nuxeoAutomationURL=http://vmjava-ged-dapplis1.univ-rennes1.fr:8880/nuxeo/site/automation

# Erreur obtenue: 

Exception in thread "main" java.lang.RuntimeException: Error reading nuxeo documents at org.esupportail.syncfsnx.domain.DomainServiceImpl.error(DomainServiceImpl.java:205) at org.esupportail.syncfsnx.domain.DomainServiceImpl.getRemoteDocuments(DomainServiceImpl.java:185) at org.esupportail.syncfsnx.domain.DomainServiceImpl.synchronise(DomainServiceImpl.java:62) at org.esupportail.syncfsnx.Launcher.main(Launcher.java:33) Caused by: java.lang.IllegalArgumentException: **No such operation: Document.Fetch** at org.nuxeo.ecm.automation.client.jaxrs.spi.DefaultSession.newRequest(DefaultSession.java:154) at org.nuxeo.ecm.automation.client.jaxrs.spi.DefaultSession.newRequest(DefaultSession.java:147) at org.esupportail.syncfsnx.domain.DomainServiceImpl.ListRemoteFolder(DomainServiceImpl.java:212) at org.esupportail.syncfsnx.domain.DomainServiceImpl.getRemoteDocuments(DomainServiceImpl.java:183)

log : 2017-01-23 11:41:16,304 INFO [org.esupportail.syncfsnx.Launcher] - Starting syncFSNX Launcher 2017-01-23 11:41:16,368 INFO [org.springframework.context.support.ClassPathXmlApplicationContext] - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@134bed0: startup date [Mon Jan 23 11:41:16 CET 2017]; root of context hierarchy 2017-01-23 11:41:16,482 INFO [org.springframework.beans.factory.xml.XmlBeanDefinitionReader] - Loading XML bean definitions from class path resource [META-INF/syncFSNX-domain-services-domain.xml] 2017-01-23 11:41:16,923 INFO [org.springframework.beans.factory.config.PropertyPlaceholderConfigurer] - Loading properties file from URL [file:/data/SIDES/Etudiants/conf-test.properties] 2017-01-23 11:41:16,940 INFO [org.springframework.beans.factory.support.DefaultListableBeanFactory] - Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@5e13ad: defining beans [domainService,configurator,propertyConfigurer]; root of factory hierarchy 2017-01-23 11:41:16,957 INFO [org.esupportail.syncfsnx.domain.DomainServiceImpl] - get local documents list 2017-01-23 11:41:16,962 INFO [org.esupportail.syncfsnx.domain.DomainServiceImpl] - get remote documents list 2017-01-23 11:41:18,109 ERROR [org.esupportail.syncfsnx.domain.DomainServiceImpl] - Error reading nuxeo documents

**Comment by hjacob35** [comment]
corrigé par @llevague
